name: R

on:
  push:
    branches: [ main ]
jobs:
  deploy-shiny:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t image_test .

      - name: execute
        run: >
          docker run
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }}
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -e MASTERNAME=${{secrets.MASTERNAME}}
          image_test
