name: R

on:
  push:
    branches: [ test ]
jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t test .

      - name: execute
        run: >
          docker run
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }}
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -e MASTERNAME=${{secrets.TESTNAME}}
          test




