name: R

on:
  push:
    branches: [ radar ]
jobs:
  deploy-shiny:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --build-arg BUILD_PALENQUE_KEY=${{ secrets.BUILD_PALENQUE_KEY }} -t image_sistema_anguil .

      - name: execute
        run: >
          docker run
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME_JP }}
          -e TOKEN=${{secrets.TOKEN_JP}}
          -e SECRET=${{secrets.SECRET_JP}}
          -e MASTERNAME=${{secrets.MASTERNAME_JP}}
          image_sistema_anguil
